name: notebooks
channels:
  - conda-forge
dependencies:
  - flake8=*
  - joblib=*
  - jupyter=*
  - jupyterlab=*
  - jupyterthemes=*
  - jupytext=*
  - matplotlib=*
  - mypy=*
  - numpy=*
  - pandas=*
  - pip=*
  - pip:
      - brunette==0.2.0
  - pytest=*
  - python-language-server[all]=0.36.2
  - scikit-learn=*
  - seaborn=*
  - theme-darcula=*
